http:
  document_root: public/ # Path to the project document root
  port: 8085 # Force the port that will be used to run the server
  preferred_port: 8085 # Preferred HTTP port [default: 8000]
  allow_http: true # Prevent auto-redirection from HTTP to HTTPS
  no_tls: true # Use HTTP instead of HTTPS
  daemon: false # Run the server in the background
  use_gzip: false # Toggle GZIP compression